### ISSUE TITLE
Support `redis` v4

### ISSUE THREAD

**Issue by alecgibson** [share/sharedb-redis-pubsub#19]
The `redis` library release a massive breaking change in [v4](https://github.com/redis/node-redis/blob/v4.0.0-rc.0/CHANGELOG.md), which — amongst other things — redefines [how a client is instantiated](https://github.com/redis/node-redis/blob/v4.0.0-rc.0/docs/client-configuration.md).

They have a (small) [migration guide](https://github.com/redis/node-redis/blob/HEAD/docs/v3-to-v4.md).

We should probably discuss the best way to add support for this version whilst maintaining backwards compatibility with previous versions.

**Comment by curran** [comment]
Agree.

Also, I wonder if this might be a good opportunity to start using peer dependencies, so folks don't end up with multiple versions of ShareDB or the redis client package. 

Currently they are normal dependencies:

    "dependencies": {
      "redis": "^2.6.0 || ^3.0.0",
      "sharedb": "^1.0.0 || ^2.0.0"
    },

**Comment by alecgibson** [comment]
I've pushed [`redis-v4`](https://github.com/share/sharedb-redis-pubsub/compare/redis-v4), which runs the test suite against each version of the driver (and fails on v4).

**Comment by tomamatics** [comment]
Any news to this? Just stumbled across the same problem.
Good news are, we can use redis client v4 in legacyMode.

`const client = createClient({
    legacyMode: true
});`

works for me.

**Comment by curran** [comment]
I've adopted the latest and version and can confirm that everything works as expected! All I needed to do was remove the `legacyMode: true` from Redis v4 client init.
