### ISSUE TITLE
Basic project documentation

### ISSUE THREAD

**Issue by matt-oakes** [share/sharedb-redis-pubsub#3]
I'm looking into ShareDB and it is not clear what the function of this project is. It would be good to have documentation which includes things like:
- What is the pub/sub system which this library is built for?
- Why would you use this Redis library over the default memory one?
- Are there any disadvantages of using this library?

**Comment by samuelkilada** [comment]
For anyone wondering how to use this library:

```
var redisPubsub = require('sharedb-redis-pubsub')(redisClient); // Redis client being an existing redis client connection

var backend = new ShareDB({db: db, pubsub: redisPubsub}); // db would be your mongo db or other storage location
```

**Comment by WinMinTun** [comment]
@samuelkilada 
var redisPubsub = require('sharedb-redis-pubsub')({client: redisClient}); need to add client field
