### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by curran** [share/sharedb-redis-pubsub#4]
The [npm redis package](https://github.com/NodeRedis/node_redis) is now at v.2.7.1, and this package is depending on version "^2.6.0".

Would a PR that upgrades the dependencies be welcome?

**Comment by houshuang** [comment]
@curran Who do we need to ask to get this done? NPM redis dependency is now two years old, but I don't think the API has changed, just speed etc. We're planning to use redis in our project for other things, and I would prefer avoiding bundling two versions of node-redis...

**Comment by curran** [comment]
@houshuang I believe the only people who can merge PRs here are @rkstedman and @nateps . Perhaps we can convince them to look at #5.

There is some other related activity that may merit a new release of `sharedb-redis-pubsub` anyway - see https://github.com/share/sharedb/pull/201

**Comment by curran** [comment]
Closed in https://github.com/share/sharedb-redis-pubsub/pull/9

Thanks @nateps !
